import { test, expect } from "@playwright/test";
import { randomUUID } from "node:crypto";

test("real-stack auth, persisted note, logout, relogin and ownership isolation", async ({ page, browser }) => {
  const email = `${randomUUID()}@example.com`;
  const password = "test-password-123";
  await page.goto("/");
  await page.getByLabel("Email", { exact: true }).fill(email);
  await page.getByLabel("Password", { exact: true }).fill(password);
  await page.getByRole("button", { name: "Create account" }).click();
  await expect(page.getByText("No notes yet.", { exact: false })).toBeVisible();
  await page.getByLabel("Note title").fill("Persistent project idea");
  await page.getByRole("button", { name: "Save note" }).click();
  await expect(page.getByRole("listitem")).toHaveText("Persistent project idea");
  await page.reload();
  await expect(page.getByRole("listitem")).toHaveText("Persistent project idea");
  const saved = await page.request.get("/api/notes");
  const [note] = await saved.json();
  await page.getByRole("button", { name: "Sign out" }).click();
  await expect(page.getByLabel("Email", { exact: true })).toBeVisible();
  expect((await page.request.get("/api/notes")).status()).toBe(401);
  await page.getByLabel("Email", { exact: true }).fill(email);
  await page.getByLabel("Password", { exact: true }).fill(password);
  await page.getByRole("button", { name: "Sign in", exact: true }).click();
  await expect(page.getByRole("listitem")).toHaveText("Persistent project idea");
  const other = await browser.newContext({ baseURL: "http://localhost:3000" });
  const second = await other.newPage();
  await second.goto("/");
  await second.getByLabel("Email", { exact: true }).fill(`${randomUUID()}@example.com`);
  await second.getByLabel("Password", { exact: true }).fill(password);
  await second.getByRole("button", { name: "Create account" }).click();
  await expect(second.getByText("No notes yet.", { exact: false })).toBeVisible();
  expect((await other.request.get(`/api/notes/${note.id}`)).status()).toBe(404);
  expect((await other.request.post("/api/notes", { data: { title: " " }, headers: { Origin: "http://localhost:3000" } })).status()).toBe(422);
  expect((await other.request.post("/api/notes", { data: { title: "bad" }, headers: { Origin: "https://evil.test" } })).status()).toBe(403);
  await second.setViewportSize({ width: 375, height: 812 });
  await expect(second.getByRole("button", { name: "Save note" })).toBeVisible();
  expect(await second.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await other.close();
});
